name: umkc-web
recipe: lamp
config:
  webroot: .
services:
  appserver:
    scanner: false
  node:
    type: node
    overrides:
      ports:
        - 3000:3000
    build:
      - npm install
      - npm install -g npx
    command: npm start
tooling:
  npm:
    service: node
  npx:
    service: node
